"""Seed a real TPC-DS store-channel warehouse where a naive dimension join inflates
sales. Unlike the retail/saas demos, the data is NOT hand-seeded: it is generated by
DuckDB's official `tpcds` extension (`CALL dsdgen(sf=...)`), so the schema and the
numbers are the industry-standard benchmark, reproducible by anyone.

The trap: store_sales and store_returns are both children of the item (and customer,
date, store) dimension. Joining a dimension to BOTH facts and summing a sales measure
cross-products each item's sales by its returns, so revenue balloons ~20x at sf=1.
That is a silent, multiplicative error on a schema no one hand-built to be trappy.

Scale factor: SQLPROCTOR_TPCDS_SF (default 1, the canonical minimum). dsdgen builds all
24 TPC-DS tables; the contract and the model prompt scope to the six store-channel
tables below.

Run: python examples/tpcds_seed.py
"""

from __future__ import annotations

import os
import pathlib

import duckdb

HERE = pathlib.Path(__file__).resolve().parent
DB_PATH = os.environ.get("SQLPROCTOR_DB", str(HERE / "tpcds.duckdb"))
DEFAULT_SF = float(os.environ.get("SQLPROCTOR_TPCDS_SF", "1"))

# The store-channel subset the model is shown (raw DDL only, no contract rules). Column
# names/types mirror what DuckDB's tpcds extension generates, so queries the model writes
# run against the real generated tables. dsdgen also builds the other 18 TPC-DS tables;
# they are simply not shown here.
SCHEMA = """
CREATE TABLE store_sales (
    ss_sold_date_sk       INTEGER,
    ss_sold_time_sk       INTEGER,
    ss_item_sk            INTEGER,
    ss_customer_sk        INTEGER,
    ss_cdemo_sk           INTEGER,
    ss_hdemo_sk           INTEGER,
    ss_addr_sk            INTEGER,
    ss_store_sk           INTEGER,
    ss_promo_sk           INTEGER,
    ss_ticket_number      INTEGER,
    ss_quantity           INTEGER,
    ss_wholesale_cost     DECIMAL(7,2),
    ss_list_price         DECIMAL(7,2),
    ss_sales_price        DECIMAL(7,2),
    ss_ext_discount_amt   DECIMAL(7,2),
    ss_ext_sales_price    DECIMAL(7,2),
    ss_ext_wholesale_cost DECIMAL(7,2),
    ss_ext_list_price     DECIMAL(7,2),
    ss_ext_tax            DECIMAL(7,2),
    ss_coupon_amt         DECIMAL(7,2),
    ss_net_paid           DECIMAL(7,2),
    ss_net_paid_inc_tax   DECIMAL(7,2),
    ss_net_profit         DECIMAL(7,2)
);
CREATE TABLE store_returns (
    sr_returned_date_sk   INTEGER,
    sr_return_time_sk     INTEGER,
    sr_item_sk            INTEGER,
    sr_customer_sk        INTEGER,
    sr_cdemo_sk           INTEGER,
    sr_hdemo_sk           INTEGER,
    sr_addr_sk            INTEGER,
    sr_store_sk           INTEGER,
    sr_reason_sk          INTEGER,
    sr_ticket_number      INTEGER,
    sr_return_quantity    INTEGER,
    sr_return_amt         DECIMAL(7,2),
    sr_return_tax         DECIMAL(7,2),
    sr_return_amt_inc_tax DECIMAL(7,2),
    sr_fee                DECIMAL(7,2),
    sr_return_ship_cost   DECIMAL(7,2),
    sr_refunded_cash      DECIMAL(7,2),
    sr_reversed_charge    DECIMAL(7,2),
    sr_store_credit       DECIMAL(7,2),
    sr_net_loss           DECIMAL(7,2)
);
CREATE TABLE item (
    i_item_sk        INTEGER,
    i_item_id        VARCHAR,
    i_rec_start_date DATE,
    i_rec_end_date   DATE,
    i_item_desc      VARCHAR,
    i_current_price  DECIMAL(7,2),
    i_wholesale_cost DECIMAL(7,2),
    i_brand_id       INTEGER,
    i_brand          VARCHAR,
    i_class_id       INTEGER,
    i_class          VARCHAR,
    i_category_id    INTEGER,
    i_category       VARCHAR,
    i_manufact_id    INTEGER,
    i_manufact       VARCHAR,
    i_size           VARCHAR,
    i_formulation    VARCHAR,
    i_color          VARCHAR,
    i_units          VARCHAR,
    i_container      VARCHAR,
    i_manager_id     INTEGER,
    i_product_name   VARCHAR
);
CREATE TABLE customer (
    c_customer_sk          INTEGER,
    c_customer_id          VARCHAR,
    c_current_cdemo_sk     INTEGER,
    c_current_hdemo_sk     INTEGER,
    c_current_addr_sk      INTEGER,
    c_first_shipto_date_sk INTEGER,
    c_first_sales_date_sk  INTEGER,
    c_salutation           VARCHAR,
    c_first_name           VARCHAR,
    c_last_name            VARCHAR,
    c_preferred_cust_flag  VARCHAR,
    c_birth_day            INTEGER,
    c_birth_month          INTEGER,
    c_birth_year           INTEGER,
    c_birth_country        VARCHAR,
    c_login                VARCHAR,
    c_email_address        VARCHAR,
    c_last_review_date_sk  INTEGER
);
CREATE TABLE date_dim (
    d_date_sk          INTEGER,
    d_date_id          VARCHAR,
    d_date             DATE,
    d_month_seq        INTEGER,
    d_week_seq         INTEGER,
    d_quarter_seq      INTEGER,
    d_year             INTEGER,
    d_dow              INTEGER,
    d_moy              INTEGER,
    d_dom              INTEGER,
    d_qoy              INTEGER,
    d_fy_year          INTEGER,
    d_fy_quarter_seq   INTEGER,
    d_fy_week_seq      INTEGER,
    d_day_name         VARCHAR,
    d_quarter_name     VARCHAR,
    d_holiday          VARCHAR,
    d_weekend          VARCHAR,
    d_following_holiday VARCHAR,
    d_first_dom        INTEGER,
    d_last_dom         INTEGER,
    d_same_day_ly      INTEGER,
    d_same_day_lq      INTEGER,
    d_current_day      VARCHAR,
    d_current_week     VARCHAR,
    d_current_month    VARCHAR,
    d_current_quarter  VARCHAR,
    d_current_year     VARCHAR
);
CREATE TABLE store (
    s_store_sk         INTEGER,
    s_store_id         VARCHAR,
    s_rec_start_date   DATE,
    s_rec_end_date     DATE,
    s_closed_date_sk   INTEGER,
    s_store_name       VARCHAR,
    s_number_employees INTEGER,
    s_floor_space      INTEGER,
    s_hours            VARCHAR,
    s_manager          VARCHAR,
    s_market_id        INTEGER,
    s_geography_class  VARCHAR,
    s_market_desc      VARCHAR,
    s_market_manager   VARCHAR,
    s_division_id      INTEGER,
    s_division_name    VARCHAR,
    s_company_id       INTEGER,
    s_company_name     VARCHAR,
    s_street_number    VARCHAR,
    s_street_name      VARCHAR,
    s_street_type      VARCHAR,
    s_suite_number     VARCHAR,
    s_city             VARCHAR,
    s_county           VARCHAR,
    s_state            VARCHAR,
    s_zip              VARCHAR,
    s_country          VARCHAR,
    s_gmt_offset       DECIMAL(5,2),
    s_tax_percentage   DECIMAL(5,2)
);
"""


def build(db_path: str = DB_PATH, *, sf: float = DEFAULT_SF) -> str:
    """Generate a real TPC-DS warehouse at scale `sf` via DuckDB's tpcds extension."""
    if os.path.exists(db_path):
        os.remove(db_path)
    con = duckdb.connect(db_path)
    con.execute("INSTALL tpcds")
    con.execute("LOAD tpcds")
    con.execute(f"CALL dsdgen(sf={sf})")
    con.close()
    return db_path


# The canonical correct answer to "total store sales" (single fact, no fan-out) verifies.
TRUE_REVENUE_SQL = """
SELECT SUM(ss.ss_net_paid) AS store_revenue
FROM store_sales ss
"""

# "Net sales after returns, by item" written the tempting way: join the item dimension
# to BOTH facts. Each item's sales rows get multiplied by its return rows (~20x at sf=1).
NAIVE_REVENUE_SQL = """
SELECT SUM(ss.ss_net_paid) AS store_revenue
FROM item i
JOIN store_sales ss   ON i.i_item_sk = ss.ss_item_sk
JOIN store_returns sr ON i.i_item_sk = sr.sr_item_sk
"""


def revenue_numbers(db_path: str = DB_PATH):
    """Returns (true_revenue, naive_revenue, ratio) from the real generated DB."""
    con = duckdb.connect(db_path, read_only=True)
    true_rev = float(con.execute(TRUE_REVENUE_SQL).fetchone()[0])
    naive_rev = float(con.execute(NAIVE_REVENUE_SQL).fetchone()[0])
    con.close()
    return true_rev, naive_rev, naive_rev / true_rev


def _counts(db_path: str):
    con = duckdb.connect(db_path, read_only=True)
    q = lambda sql: con.execute(sql).fetchone()[0]
    out = {t: q(f"SELECT COUNT(*) FROM {t}")
           for t in ("store_sales", "store_returns", "item", "customer", "store")}
    con.close()
    return out


def main() -> int:
    path = build()
    c = _counts(path)
    true_rev, naive_rev, ratio = revenue_numbers(path)
    print(f"Seeded {path}  (TPC-DS sf={DEFAULT_SF}, store channel)")
    print(f"  store_sales:     {c['store_sales']:>12,}")
    print(f"  store_returns:   {c['store_returns']:>12,}")
    print(f"  item / customer / store: {c['item']:,} / {c['customer']:,} / {c['store']:,}")
    print(f"  true store sales:  {true_rev:>18,.2f}   SUM(ss_net_paid)")
    print(f"  naive (item->sales+returns): {naive_rev:>18,.2f}")
    print(f"  inflation:         {ratio:>10.2f}x")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
